name: Package artifact and push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Package Application
      run : dotnet pack --configuration Release

    - name: Push Application
      run: dotnet nuget push "bin/Release/invoice_management.1.0.0.nupkg"  --api-key ${{ secrets.GI_TOKEN }} --source "https://github.com/sushantjadhav416"

    
